### ISSUE TITLE
Code is too large errors since recent Graal version with Argon2

### ISSUE THREAD

**Issue by lxp** [graalvm/sulong#377] opened 2016-08-10 15:03 UTC
Argon2 works fine with older Graal versions, but triggers code is too large errors with recent Graal versions.

Argon2 Debug branch: https://github.com/lxp/sulong/tree/argon2-debug

Old, working Graal version:
```
$ mx sversions
f65a828c424782db0551cab83471de46a49a5888  sulong
a9f5ed2e5289293198de31435377b76028c0c401  graal-core
fbb6bb30803df787c07b1c8131789c94acfc2761  truffle
$ mx su-tests-argon2 -Dgraal.TraceTruffleCompilation=true
[...]
[truffle] opt done         @fill_block_with_xor <opt>                                  |ASTSize   14880/14880 |Time 19526(6132+13394)ms |DirectCallNodes I    0/D  134 |GraalNodes 15053/31597 |CodeSize       137225 |Source /home/david/graalvm/sulong/projects/com.oracle.truffle.llvm.test/argon2/phc-winner-argon2/test.su@dc1216ad8495636fd6a5fa4185a38a01e515a68a_ref.ll:1 
[truffle] opt done         @fill_block <opt>                                           |ASTSize   14871/14871 |Time 19460(6866+12594)ms |DirectCallNodes I    0/D  133 |GraalNodes 15024/31477 |CodeSize       136955 |Source /home/david/graalvm/sulong/projects/com.oracle.truffle.llvm.test/argon2/phc-winner-argon2/test.su@dc1216ad8495636fd6a5fa4185a38a01e515a68a_ref.ll:1 
[...]
```

Still working, but already large code size:
```
$ mx sversions
f65a828c424782db0551cab83471de46a49a5888  sulong
e8656a2a6674f662ba2568e10327c55153d61f12  graal-core
534a0391a33938b5d20b362c3f4988e90672bf0c  truffle
$ mx su-tests-argon2 -Dgraal.TraceTruffleCompilation=true
[...]
[truffle] opt done         @fill_block_with_xor <opt>                                  |ASTSize   14880/14880 |Time 25975(6091+19884)ms |DirectCallNodes I    0/D  134 |GraalNodes 19120/76991 |CodeSize       631612 |Source /home/david/graalvm/sulong/projects/com.oracle.truffle.llvm.test/argon2/phc-winner-argon2/test.su@dc1216ad8495636fd6a5fa4185a38a01e515a68a_ref.ll:1 
[truffle] opt done         @fill_block <opt>                                           |ASTSize   14871/14871 |Time 24168(4752+19416)ms |DirectCallNodes I    0/D  133 |GraalNodes 19086/76777 |CodeSize       631817 |Source /home/david/graalvm/sulong/projects/com.oracle.truffle.llvm.test/argon2/phc-winner-argon2/test.su@dc1216ad8495636fd6a5fa4185a38a01e515a68a_ref.ll:1 
[...]
```

Most recent version, Code size too large:
```
$ mx sversions
f65a828c424782db0551cab83471de46a49a5888  sulong
daaace2f5a3d961da5eca169e32408ab5b66e2c9  graal-core
bd163128ec958b97ebc68b33ac5b4fae376a37b5  truffle
$ mx su-tests-argon2 -Dgraal.TraceTruffleCompilation=true
[truffle] opt fail         @fill_block_with_xor                                        |Reason jdk.vm.ci.code.BailoutException: Code installation failed: code is too large 
jdk.vm.ci.code.BailoutException: Code installation failed: code is too large
	at jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:140)
	at com.oracle.graal.compiler.target.Backend.createInstalledCode(Backend.java:163)
	at com.oracle.graal.truffle.TruffleCompiler.compileMethodHelper(TruffleCompiler.java:207)
	at com.oracle.graal.truffle.TruffleCompiler.compileMethod(TruffleCompiler.java:159)
	at com.oracle.graal.truffle.GraalTruffleRuntime.doCompile0(GraalTruffleRuntime.java:465)
	at com.oracle.graal.truffle.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:451)
	at com.oracle.graal.truffle.GraalTruffleRuntime$1.run(GraalTruffleRuntime.java:483)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.oracle.graal.compiler.CompilerThread.run(CompilerThread.java:51)

[truffle] opt fail         @fill_block                                                 |Reason jdk.vm.ci.code.BailoutException: Code installation failed: code is too large 
jdk.vm.ci.code.BailoutException: Code installation failed: code is too large
	at jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:140)
	at com.oracle.graal.compiler.target.Backend.createInstalledCode(Backend.java:163)
	at com.oracle.graal.truffle.TruffleCompiler.compileMethodHelper(TruffleCompiler.java:207)
	at com.oracle.graal.truffle.TruffleCompiler.compileMethod(TruffleCompiler.java:159)
	at com.oracle.graal.truffle.GraalTruffleRuntime.doCompile0(GraalTruffleRuntime.java:465)
	at com.oracle.graal.truffle.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:451)
	at com.oracle.graal.truffle.GraalTruffleRuntime$1.run(GraalTruffleRuntime.java:483)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.oracle.graal.compiler.CompilerThread.run(CompilerThread.java:51)

```

With this Graal version compilation also requires a lot of heap space.

**Comment by mrigger** [comment] 2016-08-19 08:18
The new error seems to be caused by one of the following `graal-core` commits:
```
The first bad commit could be any of:
27d992d0540236ebab7779368f94a16a93867e90
46316c8772e42a6039a8051782194eb06af340d6
17c7bc009960f4ce4c1bcb2463c848e4ec003340
7a1fa540fb89b295caf23cfcf6496c28662a9500
9e477aa7ac5999169e89c3436b74a6d92709f8c6
b1fd0df45d0945b253028e434d2d14abe84d6cc0
2f199f4f9e27ed6b089374d3741c2a50c4f4d545
We cannot bisect more!
```

**Comment by mrigger** [comment] 2016-09-14 11:55
This bug has been fixed in `graal-core`.

**Closed by mrigger** 2016-09-14 11:55 UTC
Labels: graal-core
